apiVersion: v1
kind: Service
metadata:
  labels:
    pinpoint.batch.service: pinpoint-batch
  name: pinpoint-batch-service
spec:
  ports:
    - name: batch-server
      port: COLLECTOR_RECEIVER_GRPC_AGENT_PORT
      targetPort: 8079
  selector:
    pinpoint.batch.service: pinpoint-batch
