apiVersion: v1
kind: Service
metadata:
  labels:
    pinpoint.quickstart.service: pinpoint-quickstart
  name: pinpoint-quickstart-service
spec:
  ports:
    - name: hbase-port
      port: 2180
      targetPort: APP_PORT
  selector:
    pinpoint.quickstart.service: pinpoint-quickstart
