apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    pinpoint.agent.service: pinpoint-agent
  name: pinpoint-agent-DaemonSet
spec:
  selector:
    matchLabels:
      pinpoint.agent.service: pinpoint-agent
  replicas: 1
  template:
    metadata:
      labels:
        pinpoint.agent.service: pinpoint-agent
    spec:
      containers:
        - image: pinpointdocker/pinpoint-agent:PINPOINT_VERSION
          name: pinpoint-agent
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: pinpoint-agent-config
          volumeMounts:
            - name: data-volume
              mountPath: /pinpoint-agent

      volumes:
        - name: data-volume
          emptyDir: { }


      restartPolicy: Always