apiVersion: v1
kind: Pod
metadata:
  labels:
    pinpoint.agent.service: pinpoint-agent
  name: pinpoint-agent-pod
spec:
  containers:
    - image: pinpointdocker/pinpoint-agent:PINPOINT_VERSION
      name: pinpoint-agent
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: pinpoint-agent-config
      volumeMounts:
        - name: data-volume
          mountPath: /pinpoint-agent

  volumes:
    - name: data-volume
      emptyDir: {}


  restartPolicy: Always